### ISSUE TITLE
Question: Implementing Freakduino Support

### ISSUE THREAD

**Issue by Crypt0s** [riverloopsec/killerbee#123]
I got a 900mhz Freakduino and was planning on implementing support for it in Killerbee.  I noticed that Killerbee already has support for the 2.4Ghz variant but that it was missing some features.

Were there major roadblocks in getting certain features implemented, and if so, what were they so I know what I'm getting in to?

Thanks for your time and efforts, BTW!

**Comment by rmspeers** [comment]
No issues or roadblocks that I had from a feature point of view. I have set the configuration to disable Freakduino auto-enumeration in general, as the serial connection to it is a pain as you have to "discover" it by protocol, and that can conflict with other serial loads (e.g., ApiMote). I think the best thing would be if you can get enumeration of it at least via the USB IDs, as this could help reduce conflicts when loading it. I'm not sure that this will be possible -- it likely depends on the IDs he sets on the FTDI chip.
Another option is to make the serial protocol in the Firmware the same as to the GoodFET firmware code base, so the same command can be sent and -- instead of  crashing one or getting an error -- they will both respond in-kind to enumeration. Does that make sense?
