### ISSUE TITLE
Support for ACK attack?

### ISSUE THREAD

**Issue by whoot** [riverloopsec/killerbee#183]
Hey,

just wanted to ask if support for the [ACK attack](http://www.ann.ece.ufl.edu/courses/eel6935_11fal/student_talks/Presentation_9-29-11.pdf#page=51) is planned - or even feasible?

Greetings

**Comment by rmspeers** [comment]
Hi,

That's a simple and straightforward attack, and feasible for sure. I would suggest that it be implemented in firmware though instead of on the host for best reliability and performance.

Adding it to the GoodFET CCSPI client and then having KillerBee call it (register it as a new capability, perhaps a jamming variant to trigger that way in the API).

Further optimization could be done by having 2 devices work together on it, which actually is probably needed to get good TX turn-around time on short packets.
